From the array, retrieve the values([[3,4],[5,6]]) using indexing

In [1]:
import numpy as np

In [37]:

lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [4,5,6,7,8]

arr = np.array([lst1, lst2, lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [38]:
arr.shape

(3, 5)

In [39]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 4, 5],
       [6, 7, 8]])

In [43]:
arr[1:3,1:3]

array([[3, 4],
       [5, 6]])